<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>BigTeleport</AssemblyName>
    <Description>Teleport</Description>
    <Version>1.0.2</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <BigWalkInterop>C:\Program Files (x86)\Steam\steamapps\common\Big Walk\BepInEx\interop</BigWalkInterop>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.788" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="$(BigWalkInterop)\*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>